POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5ldyB1c2VyIiwiaWQiOiI2MzYzMzExOThiMWM2ZDc4MTI1MzY2YTMiLCJpYXQiOjE2Njc0NDU0MTd9.lcn9fyiwbkjMLW7JRMIt3KflrqAg9u68qtkGGaGYZ-4

{
  "content": "valid",
  "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "err"
}