POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "valid",
  "important": true,
  "userId": "636328016c6450f19493d29e"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "err"
}